### ISSUE TITLE
Error: can't create admin account

### ISSUE THREAD

**Issue by allyssonmoscoso** [Chatnaut/Arclight#18]
Try creating admin account, but when submit form is sent, fail...

Using virtual machine on virt manager local server.

Ubuntu 22.04.1 LTS 

![Screenshot_20220818_230505](https://user-images.githubusercontent.com/56805541/185534133-c584ac1b-5bc8-4b41-9011-75c3b58e5f43.png)

**Comment by S4nfs** [comment]
@SquarePeace This is a certificate error and you are using Http instead of Https. Try Https and follow the https://docs.chatnaut.com/encrypt_arclight/self-cert.html steps if you are not using any domain.

Also try:  `service mongod start` to start the mongo service for ubuntu 22.04
