### ISSUE TITLE
Questions about the tool

### ISSUE THREAD

**Issue by cairoapcampos** [Chatnaut/Arclight#19]
Could you clear my doubts about the tool. I've been looking for a long time for a web tool to manage KVM. I don't want to use Xenserver anymore.

1- Is it possible to manage multiple QEMU/KVM nodes with the same interface?

2- Is there any official docker image?

3- With this interface is it possible to manage High Availability (HA) in KVM?

**Comment by elondust** [comment]
Clustering is not yet available in the public version but soon be included in the upcoming updates. If you have any other questions let me know.
