### ISSUE TITLE
install

### ISSUE THREAD

**Issue by TorbenMartin** [Chatnaut/Arclight#22]
hey. 

i want to give it a try. running on ubuntu 20.04.5

install complete. reboot.

Error: Arc api not running
Failed to start PM2 process manager.

**Comment by elondust** [comment]
Hello @TorbenMartin, Check if the pm2 process is running with `pm2 status` command if it's not, try to restart the process using `systemctl reload-or-restart pm2-root` and see if the arc api is listed in the process table.


![Screenshot (54)](https://user-images.githubusercontent.com/44623625/192147107-e821bc70-c8b2-44de-8f3a-ce64f05cfb07.png)

**Comment by TorbenMartin** [comment]
pm2-root not found.

pm2 status tell me status errored

**Comment by elondust** [comment]
Can you provide a detailed error message or something like a screenshot?
