### ISSUE TITLE
Arc api not running

### ISSUE THREAD

**Issue by dklinux7** [Chatnaut/Arclight#24]
Hello, I'm running ubuntu 20.04. I've installed arclight v2 using the script provided. Installation is successful. But when I login it shows "Arc api not running in ui" with red highlighter. @jonatan5524 @elondust @S4nfs Also by looking into the script I manually executed the command "pm2 start ecosystem.config.js" after reboot. Still not working.

**Comment by S4nfs** [comment]
Hi @dklinux7, Sorry to hear but has your issue been fixed or not? Also check the pm2 logs. which can help you find out why problems are occurring.  To check the logs, in terminal Just run the command `pm2 logs` and paste the output here.

**Comment by S4nfs** [comment]
Since the issue has already been discussed via email, i am closing this one. If you have additional questions or concerns, please feel free to open an another.
